# Generated by Django 4.1.6 on 2023-08-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='snaps')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
